version: 2.1

orbs:
  coverage-reporter: codacy/coverage-reporter@11.10.0

executors:
  python36-docker:
    docker:
      - image: cimg/python:3.6.10
    resource_class: medium

commands:
  setup_test_translation_under_coverage:
    steps:
      - checkout
      - run:
          name: "Install package"
          command: |
            pip install .[dev]
      - run:
          name: "Test translation under coverage"
          command: |
            coverage run -m pytest tests/test_en_to_vi.py
            coverage xml
      - coverage-reporter/send_report:
          coverage-reports: 'coverage.xml'
          project-token: $CODACY_PROJECT_TOKEN

      
jobs:
  test_urbans:
    executor: python36-docker
    steps:
      - setup_test_translation_under_coverage

workflows:
  # Name the workflow "welcome"
  main:
    # Run the welcome/run job in its own container
    jobs:
      - test_urbans
